export interface Hackathon {
  id: string;
  name: string;
  city: string;
  date: string;
  endDate: string;
  venue: string;
  address: string;
  format: 'in-person' | 'hybrid';
  description: string;
  maxParticipants: number;
  registeredParticipants: number;
  website: string;
  image: string;
  tags: string[];
  prizes: string;
  contact: string;
  approved: boolean;
}

export const cities = [
  { name: 'Berlin', slug: 'berlin' },
  { name: 'Munich', slug: 'munich' },
  { name: 'Hamburg', slug: 'hamburg' },
  { name: 'Frankfurt', slug: 'frankfurt' },
  { name: 'Cologne', slug: 'cologne' },
  { name: 'Darmstadt', slug: 'darmstadt' },
  { name: 'Mannheim', slug: 'mannheim' },
  { name: 'Karlsruhe', slug: 'karlsruhe' },
  { name: 'Offenburg', slug: 'offenburg' },
  { name: 'Freiburg im Breisgau', slug: 'freiburg-im-breisgau' },
];

export const hackathons: Hackathon[] = [
  {
    id: 'kill-the-search-bar-pdm-2026',
    name: 'Kill the Search Bar - pdm Hackathon 2026',
    city: 'Berlin',
    date: '2026-05-15',
    endDate: '2026-05-17',
    venue: 'pdm solutions GmbH',
    address: 'Boxhagener Str. 78, 10245 Berlin, Germany',
    format: 'in-person',
    description: 'A builders-only hackathon to reinvent the directory ecosystem in Germany. 6 curated teams tackle real industry pain points—no panels, no small talk, just 72 hours of focused building. Challenges include AI-native interfaces, embedded booking, live-data engines, and more. Demo Day on May 20 at the VDAV Industry Meetup.',
    maxParticipants: 30,
    registeredParticipants: 5,
    website: 'https://luma.com/2e3aa6yj',
    image: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=280,height=280/gallery-images/fv/9ca2825f-781f-48c2-bc21-7dd90ac2d3ef',
    tags: ['AI', 'Directories', 'SMB', 'Berlin'],
    prizes: '€3,000+ curated prize package, CEO pitch sessions, industry opportunities',
    contact: '',
    approved: true,
  },
  {
    id: 'healthcare-hackathon-berlin-2026',
    name: 'Healthcare Hackathon Berlin 2026',
    city: 'Berlin',
    date: '2026-07-08',
    endDate: '2026-07-10',
    venue: 'In den Ministeriengärten 8',
    address: 'In den Ministeriengärten 8, 10117 Berlin, Germany',
    format: 'in-person',
    description: 'Three days of innovation, open source, next-generation hospital information systems, and digital transformation – together with leading minds from clinics, politics, and technology. 12 interdisciplinary challenges, keynotes, panels, and over 400 participants. Organized by UKSH, PwC & Google.',
    maxParticipants: 400,
    registeredParticipants: 282,
    website: 'https://healthcare-hackathon.de/',
    image: 'https://healthcare-hackathon.de/logo-color.svg',
    tags: ['Healthcare', 'AI', 'Open Source', 'Berlin', 'Digital Health'],
    prizes: 'Material prizes, credits, licenses, networking with industry leaders',
    contact: '',
    approved: true,
  },
    {
      id: 'xdesign-hackathon-berlin-2026',
      name: 'XDesign Hackathon x CODE x Lovable x Langdock x Superchat x Knowunity x SPACING',
      city: 'Berlin',
      date: '2026-04-18',
      endDate: '2026-04-18',
      venue: 'CODE University of Applied Sciences',
      address: 'Donaustraße 44, 12043 Berlin, Germany',
      format: 'in-person',
      description: "A one-day sprint for designers, builders, and founders to explore where product thinking meets fast execution. Industry tracks with real-world challenges, wild track for your own ideas, panel talks, and prizes for best design and execution. Sponsored by CODE University, Lovable, Langdock, Superchat, Knowunity, SPACING, Wonder, and Berlin Design. Hosted by Noë Hecker, Lilly Wallawitsch, Tara Schlosser & Anja Finnegan.",
      maxParticipants: 200,
      registeredParticipants: 162,
      website: 'https://luma.com/8801rq13',
      image: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=280,height=280/event-covers/22/bf1529f7-185c-4503-bfad-97fbb09b8fff.png',
      tags: ['AI', 'Design', 'Berlin', 'Product', 'CODE University', 'Lovable', 'Langdock', 'Superchat', 'Knowunity', 'SPACING'],
      prizes: 'Free Lovable credits, awards for best design and best execution (tba)',
      contact: 'leo.nguyen24112005@gmail.com',
      approved: true,
    },
  {
    id: 'hackxplore-2026',
    name: 'HackXplore 2026',
    city: 'Karlsruhe',
    date: '2026-06-26',
    endDate: '2026-06-28',
    venue: 'SteamWork by GoodSpaces',
    address: 'SteamWork by GoodSpaces, Karlsruhe, Germany',
    format: 'in-person',
    description: 'A 3-day hackathon for young professionals in Karlsruhe. Interdisciplinary teams tackle real challenges from industry partners, compete for a big prize pool, and build valuable networks. Organized by NXTGN and MESH, under the patronage of the Ministry of Science, Research and Arts of Baden-Württemberg.',
    maxParticipants: 150,
    registeredParticipants: 150,
    website: 'https://hackxplore.de/',
    image: 'https://hackxplore.de/wp-content/uploads/2025/11/HackXplore2025-364-1024x683.jpg',
    tags: ['Innovation', 'Young Professionals', 'Karlsruhe', 'Industry', 'Networking'],
    prizes: 'Big prize pool (cash & more)',
    contact: '',
    approved: true,
  },
  {
    id: 'tum-science-hackathon-2026',
    name: 'TUM Science Hackathon 2026',
    city: 'Munich',
    date: '2026-06-19',
    endDate: '2026-06-21',
    venue: 'Technical University of Munich',
    address: 'Arcisstrasse 21, 80333 Munich, Germany',
    format: 'in-person',
    description: 'A 3-day hackathon where interdisciplinary student teams solve real-world challenges from industry and research. Hosted by TUM Junge Akademie, the event blends rapid innovation, academic excellence, and entrepreneurial spirit.',
    maxParticipants: 150,
    registeredParticipants: 150,
    website: 'https://www.ja.tum.de/ja/sciencehackathon/',
    image: 'https://www.ja.tum.de/fileadmin/_processed_/7/4/csm_ScienceHack-25_group_header_6fcf02bbe4.png',
    tags: ['Science', 'Students', 'Munich', 'Innovation', 'TUM'],
    prizes: 'Recognition, networking, and more',
    contact: '',
    approved: true,
  },
  {
    id: 'big-berlin-hack-2026',
    name: 'Big Berlin Hack',
    city: 'Berlin',
    date: '2026-04-25',
    endDate: '2026-04-26',
    venue: 'The Delta Campus',
    address: 'Berlin, Germany',
    format: 'in-person',
    description: 'A weekend of innovation, collaboration, and building the future of AI. Over 300 builders, more than €50,000 in prizes, and top partners like Google DeepMind. Hosted by Tech:Europe, CODE University, and The Delta Campus.',
    maxParticipants: 300,
    registeredParticipants: 300,
    website: 'https://luma.com/bigberlinhack',
    image: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=280,height=280/event-covers/1l/d2466a90-f3b2-4c67-b856-4aaa6696e762.png',
    tags: ['AI', 'Berlin', 'Builders', 'Collaboration', 'Prizes'],
    prizes: 'Over €50,000 in prizes',
    contact: '',
    approved: true,
  },
  {
    id: 'q-hackathon-2026',
    name: 'Q-Hackathon 2026',
    city: 'Mannheim',
    date: '2026-04-08',
    endDate: '2026-04-09',
    venue: 'Baroque Palace, University of Mannheim',
    address: 'Schloss Ehrenhof Ost, 68161 Mannheim, Germany',
    format: 'in-person',
    description: '24 hours of hacking, 1 big pitch battle. Compete with ambitious students from 40+ countries and Europe’s top universities. Solve real-world challenges from top partners, enjoy free Q-Summit tickets, afterparty, catering, and accommodation.',
    maxParticipants: 200,
    registeredParticipants: 200,
    website: 'https://luma.com/79ly3pds',
    image: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=280,height=280/event-covers/lr/bbeebf00-633f-438c-859b-42497f5aedce.jpg',
    tags: ['Students', 'Mannheim', 'Q-Summit', 'Pitch', 'Prizes'],
    prizes: 'Cash prizes, exclusive non-cash prizes, goodie bags',
    contact: '',
    approved: true,
  },
  {
    id: 'black-forest-hackathon-2026',
    name: 'Black Forest Hackathon 2026',
    city: 'Offenburg',
    date: '2026-05-08',
    endDate: '2026-05-10',
    venue: 'flow1986',
    address: 'Am alten Schlachthof 14, 77652 Offenburg, Germany',
    format: 'in-person',
    description: 'The Black Forest Hackathon is the meeting place for visionaries who want to spend a weekend working with the latest technologies in a unique environment. Join 100+ hackers from all backgrounds to solve Smart Region challenges in data, AI, energy, mobility, and sustainability. Enjoy €6,000 in cash prizes, free participation, all meals included, exclusive tools, and top networking opportunities. Mentorship, swag, and career connections await in this 48-hour, on-site event.',
    maxParticipants: 100,
    registeredParticipants: 0,
    website: 'https://www.blackforesthackathon.de/smartregion/',
    image: 'https://www.blackforesthackathon.de/wp-content/uploads/2023/06/BlackForestHackathon_Logo.png',
    tags: ['Smart Region', 'Black Forest', 'Offenburg', 'AI', 'Sustainability', 'Mobility', 'Energy', 'Data'],
    prizes: '€6,000 in cash prizes, swag, and more',
    contact: '',
    approved: true,
  },
  {
    id: 'black-forest-hackathon-pentest-2026',
    name: 'Black Forest Hackathon – Pentest Edition',
    city: 'Freiburg im Breisgau',
    date: '2026-06-12',
    endDate: '2026-06-14',
    venue: 'Badenova Forum',
    address: 'Tullastr. 61, 79108 Freiburg im Breisgau, Germany',
    format: 'hybrid',
    description: 'The Pentest Edition of the Black Forest Hackathon is a hybrid event for 20 selected pentesters and security enthusiasts. Kick off in-person in Freiburg, then hack online for 48 hours. Compete for €10,000 in cash prizes, network with Badenova and peers, and enjoy free participation, swag, and career opportunities. Application required. Award ceremony and networking dinner the following Friday.',
    maxParticipants: 20,
    registeredParticipants: 0,
    website: 'https://www.blackforesthackathon.de/badenova-pentest/',
    image: 'https://www.blackforesthackathon.de/wp-content/uploads/2023/06/BlackForestHackathon_Logo.png',
    tags: ['Pentest', 'Security', 'Hybrid', 'Freiburg', 'Hacking', 'Networking'],
    prizes: '€10,000 in cash prizes, swag, and more',
    contact: '',
    approved: true,
  },
  {
    id: 'berlin-robotics-agentic-coding-hackathon-2026',
    name: 'Berlin Robotics x Agentic Coding Hackathon',
    city: 'Berlin',
    date: '2026-06-20',
    endDate: '2026-06-21',
    venue: 'Berlin',
    address: 'Berlin, Germany',
    format: 'in-person',
    description: 'Join the first edition of the Berlin Robotics x Agentic Coding Hackathon—a weekend of innovation, collaboration, and building the future of robotics and AI. Open to robotics engineers, software developers, designers, and entrepreneurs. Work hands-on with agentic coding and robotics hardware, get mentorship from industry leaders, and network with top-tier investors and founders. Present your project to a jury of tech pioneers and compete for prizes.',
    maxParticipants: 100,
    registeredParticipants: 0,
    website: 'https://www.eventbrite.com/e/berlin-robotics-x-agentic-coding-hackathon-tickets-1986078420018',
    image: 'https://www.eventbrite.com/e/_next/image?url=https%3A%2F%2Fimg.evbuc.com%2Fhttps%253A%252F%252Fcdn.evbuc.com%252Fimages%252F1180897288%252F2996656448683%252F1%252Foriginal.20260328-133133%3Fcrop%3Dfocalpoint%26fit%3Dcrop%26w%3D1880%26auto%3Dformat%252Ccompress%26q%3D75%26sharp%3D10%26fp-x%3D0.5%26fp-y%3D0.5%26s%3D4631e300ed3e1c9c915d363d39288179&w=1880&q=75',
    tags: ['Robotics', 'Agentic Coding', 'AI', 'Berlin', 'Innovation'],
    prizes: 'Prizes for top teams and projects',
    contact: '',
    approved: true,
  },
  {
    id: 'cheftreff-ai-hackathon-2026',
    name: 'ChefTreff AI Hackathon',
    city: 'Hamburg',
    date: '2026-04-09',
    endDate: '2026-04-10',
    venue: 'Factory Hammerbrooklyn',
    address: 'Stadtdeich 2-4, 20097 Hamburg, Germany',
    format: 'in-person',
    description: 'Join the ChefTreff AI Hackathon in Hamburg for a weekend of building, learning, and networking. Collaborate with students, founders, and tech enthusiasts to create AI-powered solutions for the future of commerce and society. Enjoy workshops, mentorship, and the chance to win prizes in a vibrant, hands-on environment.',
    maxParticipants: 120,
    registeredParticipants: 0,
    website: 'https://luma.com/cheftreff-ai-hackathon',
    image: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=280,height=280/gallery-images/ly/6e401872-c970-4cd1-8961-20f714b9dcf3',
    tags: ['AI', 'Hackathon', 'Hamburg', 'Students', 'Innovation'],
    prizes: 'Prizes for top teams and projects',
    contact: '',
    approved: true,
  },
  {
    id: 'agentic-commerce-x402-hackathon-2026',
    name: 'Algorand Builders Berlin: Agentic Commerce x402 Hackathon',
    city: 'Berlin',
    date: '2026-05-29',
    endDate: '2026-05-31',
    venue: '42 Berlin',
    address: 'Harzer Str. 42, 12059 Berlin, Germany',
    format: 'in-person',
    description: 'Join the Algorand Builders Berlin: Agentic Commerce x402 Hackathon for a 50-hour, on-site event focused on building the future of internet-native payments, DeFi, tokenization, and agentic commerce. Compete for a $20,000 USDC prize pool, get mentorship, workshops, and connect with the Algorand ecosystem. Open to all builders, developers, designers, and entrepreneurs. Food and beverages provided, overnight access to the hackathon space.',
    maxParticipants: 120,
    registeredParticipants: 0,
    website: 'https://luma.com/agentic-commerce-hack',
    image: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=280,height=280/event-covers/6q/aaf9e4d4-4115-41fc-a9d6-3172d0a82ba5.webp',
    tags: ['AI', 'Payments', 'DeFi', 'Berlin', 'Hackathon', 'Algorand', 'x402', 'Tokenization'],
    prizes: '$20,000 USDC prize pool, milestone rewards, ecosystem support',
    contact: '',
    approved: true,
  },
    {
      id: 'codex-community-hackathon-munich-2026',
      name: 'Codex Community Hackathon with thinc! and Entrepreneurs First',
      city: 'Munich',
      date: '2026-04-18',
      endDate: '2026-04-19',
      venue: 'Wemolo HQ',
      address: 'Munich, Bavaria, Germany',
      format: 'in-person',
      description: "Munich's first Codex community hackathon! 60 builders, 30 hours, one weekend to ship a real AI product. Industrial AI cases from Manex AI, comstruct and more. Full-stack credits from Codex, Make, Lovable and Langdock. Investors from Entrepreneurs First and UVC Partners. Venue with sauna, cold plunge, and smoothie bar. Designed for builders curious about Codex, AI tools, and agentic software engineering. No prior experience required, but some coding familiarity recommended.",
      maxParticipants: 60,
      registeredParticipants: 0,
      website: 'https://luma.com/pvtcprxu',
      image: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=280,height=280/event-covers/r4/c82a039f-d88c-4bc8-98f7-3a87d4a7218c.png',
      tags: ['AI', 'Munich', 'Codex', 'Entrepreneurs First', 'thinc!', 'Agentic Software'],
      prizes: '1st: $10,000 OpenAI API credits; 2nd: $5,000 OpenAI API credits; 3rd: $1,000 OpenAI API credits; Top 5 teams: 1 year ChatGPT Pro; more TBA',
      contact: '',
      approved: true,
    },
    {
      id: 'founder-hackathon-hamburg-2026',
      name: 'Founder Hackathon: Build Fast & Get Funded',
      city: 'Hamburg',
      date: '2026-06-06',
      endDate: '2026-06-06',
      venue: 'Wunder Mobility Hamburg',
      address: 'Hongkongstraße 2-4, 20457 Hamburg, Germany',
      format: 'in-person',
      description: 'A one-day founder-focused hackathon to build fast, pitch to VCs, and get feedback from founders and investors. Join 150 selected participants for a full day of building, mentoring, and pitching.',
      maxParticipants: 150,
      registeredParticipants: 0,
      website: 'https://luma.com/hmqh70k1',
      image: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=400,height=400/uploads/11/14b7f8d6-d395-46d3-ae9a-a45812e19986.png',
      tags: ['Founder', 'Startup', 'Hamburg', 'AI BEAVERS'],
      prizes: '',
      contact: 'support@luma.com',
      approved: true,
    },
    {
      id: 'munich-ai-hackathon-2026',
      name: 'AI Hackathon – Munich Edition',
      city: 'Munich',
      date: '2026-06-13',
      endDate: '2026-06-14',
      venue: 'Tacto',
      address: 'Sandstraße 33, 80335 München, Germany',
      format: 'in-person',
      description: 'A weekend AI hackathon hosted by {Tech: Europe} and partners—build, learn, and pitch cutting-edge AI solutions. Limited to 90 participants with mentorship, networking, and a €5,000 prize pool.',
      maxParticipants: 90,
      registeredParticipants: 0,
      website: 'https://luma.com/munich-hackathon',
      image: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=400,height=400/uploads/rc/7c955648-ee68-4c02-822b-2e98f25bd454.png',
      tags: ['AI', 'Munich', 'Tech: Europe', 'Tacto', 'DeepMind'],
      prizes: '€5,000 prize pool',
      contact: '',
      approved: true,
    },
];

export function getHackathonsByCity(city: string): Hackathon[] {
  return hackathons.filter(h => h.city.toLowerCase() === city.toLowerCase() && h.approved);
}

export function getHackathonById(id: string): Hackathon | undefined {
  return hackathons.find(h => h.id === id && h.approved);
}

export function getAllApprovedHackathons(): Hackathon[] {
  return hackathons.filter(h => h.approved);
}

export function getUpcomingHackathons(): Hackathon[] {
  const now = new Date();
  return hackathons
    .filter(h => h.approved && new Date(h.date) > now)
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
}
